### ISSUE TITLE
how does this interfere with another running automations / node-red flows?

### ISSUE THREAD

**Issue by hugalafutro** [claytonjn/hass-circadian_lighting#101]
I guess I'm having trouble understanding how does this handle interference with other automations or scenes, say I have 4 lights that support changing color temp so I set them with this integration, but then if I change their brightness or color via scene or automation or node-red flow, what happens? 

Does this act as a sort of a overarching supervisor that will resume the color temp once the light returns to the state it was before the scene or automation / on next turning on of the light / or does it just stays overriden? Otherwise how does this work unless you can't change the lights this controls?  Or does it override the temp while retaining the brightness from the scene / automation etc?

**Comment by claytonjn** [comment]
Basically if the Circadian Lighting switch is turned on, any time one of the configured lights is turned on, and every `interval`, CL will set the lights to the "proper" values. If you want the lights to be anything different simply turn off the CL switch from the automation or flow before setting the lights.

**Comment by hugalafutro** [comment]
thanks that makes sense.
