### ISSUE TITLE
Feature Request: When lights is a color don't change it

### ISSUE THREAD

**Issue by poudenes** [claytonjn/hass-circadian_lighting#124]
Hi All,

I'm struggling now for weeks how to manage some things:
I use scenes for some moments (halloween at this moment months October, Christmas, kingsday (Netherlands)), then my lights have a color instead of a kelvin color. But when Circardian is enable it always change the color back to kelvin.

Is it possible to have a feature in the config something like:

```
leave_color_alone: true
```

So when lights are colored then circadian leave them alone? If this is not possible I need to script this hard in all my automations... Its a hard job haha because I need do this for every bulb (12 total) in 4 holiday scenes, in 4 scenes (TV, AppleTV, Kodi, Normal)  

Cheers,

**Comment by basnijholt** [comment]
Check out https://github.com/home-assistant/core/pull/40626 where this is already implemented.

**Comment by poudenes** [comment]
is this a add-on above circadian lighting, or a full on its own add-on?

**Comment by basnijholt** [comment]
It's not an add-on it is an integration. That integration is based on this integration and can fully replace it.

Read the top-most line of the link I posted above to see how to use it. The documentation isn't complete, so I recommend using the UI to add adaptive_lighting switches.

**Comment by poudenes** [comment]
> It's not an add-on it is an integration. That integration is based on this integration and can fully replace it.
> 
> Read the top-most line of the link I posted above to see how to use it. The documentation isn't complete, so I recommend using the UI to add adaptive_lighting switches.

Im already play with it and figure out how it work. When add a new integration, add light entity and try it. its not work. When I add a config using configuration.yaml that one is working. 

disable_entity: can be used to disable it so it won't change lights is that correct?
