### ISSUE TITLE
404: Change HACS link on installation instruction page to reflect correct address

### ISSUE THREAD

**Issue by Kylespamaccoun7** [claytonjn/hass-circadian_lighting#132]
url: [https://github.com/claytonjn/hass-circadian_lighting/wiki/Installation-Instructions](https://github.com/claytonjn/hass-circadian_lighting/wiki/Installation-Instructions)

1. click on HACS, under installation instructions
2. returns 404.
Link currently goes to: [https://custom-components.github.io/hacs/](https://custom-components.github.io/hacs/)
correct link: [https://hacs.xyz/](https://hacs.xyz/)

Thank you for all your work. I've been using your component for a while now, without issue.

**Comment by claytonjn** [comment]
Fixed, thanks!
