### ISSUE TITLE
Stable enough to release 2.0?

### ISSUE THREAD

**Issue by haivala** [claytonjn/hass-circadian_lighting#135]
2.beta has been released a while ago. Just wondering could the actual 2.0 release be done already?

**Comment by basnijholt** [comment]
￼I made most changes for that beta, however, at some point I continued the work here https://github.com/home-assistant/core/pull/40626 to integrate it into core. It's still awaiting review but it already has a lot of beta testers.

**Comment by basnijholt** [comment]
I have that code mirrored here https://github.com/basnijholt/adaptive-lighting by the way.

**Comment by haivala** [comment]
ok! installed that beta! thank you!
