### ISSUE TITLE
[Question] Hardware needed to run CL

### ISSUE THREAD

**Issue by VivantSenior** [claytonjn/hass-circadian_lighting#136]
Hi,

I would like to start using CL but can't find any information which light sources should I use. I had some thoughts and if RGB is required I was thinking about using dimmable [RGB+CCT](https://www.aliexpress.com/item/32880776288.html) LED strip otherwise just dimmable LED [WW + CW.](https://www.aliexpress.com/item/32952607768.html) As a brain I wanted to use [QuinLED Deca](https://quinled.info/2018/09/08/quinled-deca/). What are the minimum hardware requirements to use CL?

Best,
Viv

**Comment by Matoran** [comment]
Hi, you can use it with any light integrated with home assistant. The controller should run ESPHome.
Config for RGB+CCT:
https://esphome.io/components/light/rgbww.html
CCT:
https://esphome.io/components/light/cwww.html
CCT will give you something like that on home assistant
![image](https://user-images.githubusercontent.com/4539516/106180497-a8d11800-619c-11eb-8742-65ff752177ce.png)
hass-circadian_lighting is only adjusting theses values :)

**Comment by VivantSenior** [comment]
@Matoran thank you. So in order to have a best expirience with CL the minimum hardware required is CCT LED strip?

**Comment by Matoran** [comment]
Exactly, choose good quality CCT LED strip (like the one from Auxma recommended by Quindor). Having a good CRI/power is essential to have a good experience in everyday usage.
The temperature is given by mixing cold white and warm white (handled by the software by powering more one than other).

**Comment by VivantSenior** [comment]
Thank you.
