### ISSUE TITLE
Exclude specific entities from being controlled by switch

### ISSUE THREAD

**Issue by armandomisc** [claytonjn/hass-circadian_lighting#142]
I have lights that are on a schedule and some that are controlled by motion sensor. 

Is there a way to exclude these lights from circadian's control? Otherwise they're perpetually on unless I manually switch them off.

**Comment by claytonjn** [comment]
Just define multiple Circadian Lighting switches and turn the CL switches off as needed.

**Comment by armandomisc** [comment]
My bad. I completely forgot how I configured in the first place. I went through and only added the lights I wanted and now it works. Thanks for reminding me.
