### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'circadian_lighting'

### ISSUE THREAD

**Issue by XxCabbyoO** [claytonjn/hass-circadian_lighting#145]
No 'version' key in the manifest file for custom integration 'circadian_lighting'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'circadian_lighting'

**Comment by dapuzz** [comment]
The pull request has already been created
https://github.com/claytonjn/hass-circadian_lighting/pull/141

**Comment by claytonjn** [comment]
Sorry for my absence, I have a new puppy and job that have been keeping me busy!

 This has been implemented in version 2.0.4-beta, which also changes the component to be async along with a couple other changes. Please test and let me know if everything is working properly - if so I will push to a general release. Thanks!

**Comment by claytonjn** [comment]
Got a handful of people confirming that 2.0.4 is working properly and no complaints about compatibility with HA Core 2015.5.x so I'm going to close this issue. Thanks everyone!
