### ISSUE TITLE
circadian_values sensor shows on map

### ISSUE THREAD

**Issue by sinker1345** [claytonjn/hass-circadian_lighting#15]
the sensor.circadian_values sensor shows on the map page when configured. It appears to show because it has a lat and long value.

**Comment by claytonjn** [comment]
Yes, that seems to be why. I posted a poll here for feedback on whether these (and other) configuration values should be included as attributes and it seems the prevailing opinion is to remove them:

https://community.home-assistant.io/t/circadian-lighting-custom-component/61246/355

**Comment by claytonjn** [comment]
Closed by f3a1a7388517d8d48e2095bcc7cce9373c64e937
