### ISSUE TITLE
Does not work, please update

### ISSUE THREAD

**Issue by Jurgenn22** [claytonjn/hass-circadian_lighting#154]
@claytonjn 
Is this integration still being maintained? At the moment it does not work in Home Assistant, due to a New Version of Astral and changes to sun.

There is a workaround in a fork of this integration, by robertomano24.

But would like to see an update to this integration.

Like to hear from you.

**Comment by TheGroundZero** [comment]
See #148 and #149

**Comment by basnijholt** [comment]
For the time being you might try out the adaptive-lighting integration ([see this PR in core](https://github.com/home-assistant/core/pull/40626).)

The code also lives here https://github.com/basnijholt/adaptive-lighting (add as custom repo to HACS).

This code is based on this integration and has some extra features.

**Comment by Jurgenn22** [comment]
@basnijholt 
Yes up and running, thx!

**Comment by Jurgenn22** [comment]
@basnijholt 
Some help please.
I just can't control the Hue lights outside of Home Assistant, with for example the Hue App, even though "take_over_control" and "detect_non_ha_changes" are on. 
Even if I turn the lights off within Home Assistant, they automatically turn on again. I first have to turn off the adaptive lights switches, and only then can I operate the lights.

**Comment by spencerthayer** [comment]
How long until this is fixed. 😮‍💨 The [Adaptive Lighting](https://github.com/basnijholt/adaptive-lighting) integration just isn't very good.

**Comment by robertomano24** [comment]
@spencerthayer I agree. Here is a fork that works: https://github.com/robertomano24/circadian_lighting
I will do my best to keep this fork updated to work with HA. It should be working now. You will need to add the files to your custom_components folder manually. 

If you use Hue and want the Hue scenes you make to update with CL values for a seamless integration, check out my repo here: https://github.com/robertomano24/circadian_lighting-hue

**Comment by Jurgenn22** [comment]
@spencerthayer 
How do we know when an update of the files of this fork https://github.com/robertomano24/circadian_lighting is available?

**Comment by Jurgenn22** [comment]
> @spencerthayer
> How do we know when an update of the files of this fork https://github.com/robertomano24/circadian_lighting is available?

Never mind, could add your repo in hacs

**Comment by Jurgenn22** [comment]
> @spencerthayer I agree. Here is a fork that works: https://github.com/robertomano24/circadian_lighting
> I will do my best to keep this fork updated to work with HA. It should be working now. You will need to add the files to your custom_components folder manually.
> 
> If you use Hue and want the Hue scenes you make to update with CL values for a seamless integration, check out my repo here: https://github.com/robertomano24/circadian_lighting-hue

@robertomano24 
How do we know when an update of the files of this fork https://github.com/robertomano24/circadian_lighting is available?

Never mind, could add your repo in hacs

**Comment by basnijholt** [comment]
What’s your guy’s problem with Adaptive Lighting?  It does everything that circadian lighting does, but then a lot more.

**Comment by Jurgenn22** [comment]
> What’s your guy’s problem with Adaptive Lighting? It does everything that circadian lighting does, but then a lot more.

Operating / switching off Hue lamps with the Hue app does not work, despite the settings for take over. Lamps will then automatically turn on again.

**Comment by basnijholt** [comment]
Then you should just turn off that feature and you will end up with circadian lighting like behavior.

**Comment by Jurgenn22** [comment]
> Then you should just turn off that feature ( take over control) and you will end up with circadian lighting like behavior.

Tried too, doesn't work.

**Comment by basnijholt** [comment]
OK that is surprising. Unfortunately I don’t know what the problem might be without more information.

**Comment by Jurgenn22** [comment]
> OK that is surprising. Unfortunately I don’t know what the problem might be without more information.

I get that, but have now installed a fork of circadian lighting, which is being maintained, instead of the original integration.

**Comment by spencerthayer** [comment]
> What’s your guy’s problem with Adaptive Lighting? It does everything that circadian lighting does, but then a lot more.

I agree @basnijholt most use cases Adaptive Lighting is better for most people. Mine use case is very specific. I am running three versions of Circadian Lighting and I'm using them to drastically change colors between **Astronomical Dawn – Sunrise** from **Sunrise – Sunset ** and finally from **Golden Hour – Astronimcal Dusk**. It's a bit of a hack but it works most of the time. I can't get it to work with [Adaptive Lighting](https://github.com/basnijholt/adaptive-lighting).

If you are the creator I would love to request that you build into your code the ability to customize the color between various categories of the day. I actually have an [open ticket](https://github.com/basnijholt/adaptive-lighting/issues/100) for this request but it didn't seem to get any steam.

**Comment by robertomano24** [comment]
> > @spencerthayer I agree. Here is a fork that works: https://github.com/robertomano24/circadian_lighting
> > I will do my best to keep this fork updated to work with HA. It should be working now. You will need to add the files to your custom_components folder manually.
> > If you use Hue and want the Hue scenes you make to update with CL values for a seamless integration, check out my repo here: https://github.com/robertomano24/circadian_lighting-hue
> 
> @robertomano24
> How do we know when an update of the files of this fork https://github.com/robertomano24/circadian_lighting is available?

@Jurgenn22 I suppose at some point once I am certain Clayton does not plan to make updates to this repo, I will either request ownership/admin rights on the GitHub or simply add the files to a new repo all together. I currently have a different fork of this repo built SPECIFICALLY to integrate better with Hue, already. So perhaps that will come sooner than later. You can, until then, subscribe to the fork by "starring" it. 

Here is the Hue specific fork: https://github.com/robertomano24/circadian_lighting-hue

**Comment by claytonjn** [comment]
This integration is being maintained, I plan to update as soon as possible (which will likely be next week). @robertomano24 thank you for providing a fork in the meantime although it should be trivial for users of Home Assistant to just copy changes from PRs. I'm interested in what changes you've made specifically for Hue, as I have almost exclusively Hue lights throughout my house so obviously this integration, while being generic for all light entities, has been heavily tested on Hue products.

**Comment by robertomano24** [comment]
@claytonjn awesome! so glad to hear you're still working on this project! I have two forks, technically, at this point. The one associated with your repo is actually just updated to work with HA, keeping the rest of the sensor.py in-tact. The one that makes major sensor.py changes is here: https://github.com/robertomano24/circadian_lighting-hue
My most recent modifications grab the Hue API and IP from .storage automatically. Hopefully it will be useful to you for future updates!

**Comment by claytonjn** [comment]
Sorry for my absence, I have a new puppy and job that have been keeping me busy!

 This has been implemented in version 2.0.4-beta, which also changes the component to be async along with a couple other changes. Please test and let me know if everything is working properly - if so I will push to a general release. Thanks!

**Comment by TATERxxWARDY** [comment]
version 2.0.4-beta is working for me and error alert disappeared!
HA Core: core-2021.5.5
Supervisor: supervisor-2021.05.3
OS: Ubuntu 20.10
Docker: 20.10.5

**Comment by claytonjn** [comment]
Got a handful of people confirming that 2.0.4 is working properly and no complaints about compatibility with HA Core 2015.5.x so I'm going to close this issue. Thanks everyone!
