### ISSUE TITLE
Circadian Sensor not shown

### ISSUE THREAD

**Issue by clipse2004** [claytonjn/hass-circadian_lighting#155]
Hello people, 

I'm getting desperate :), I installed the Circadian Lighting via HACS and then pulled the patch over it (just copied it in). So far it seems to work, but I can't find the sensor that is supposed to be created with "sensor.circadian_values" anywhere. 
Do I have to add something to the configuration?

Merci

**Comment by robertomano24** [comment]
@clipse2004 you need the minimum added to your configuration.yaml

```
# Example configuration.yaml entry
circadian_lighting:
```
You can see how I have mine setup specifically here: https://github.com/robertomano24/home-assistant/blob/master/configuration.yaml

Hope this helps!
