### ISSUE TITLE
Avoid creating a _lot_ of events

### ISSUE THREAD

**Issue by marhoy** [claytonjn/hass-circadian_lighting#20]
I have a lot of Hue bulbs that are controlled by a RaspBee controller.

The brightness and color_temp values only have a certain resolution, which means that they cannot be set to any number. As circadian_lighting is trying to change the values smoothly, this generates a _lot_ of events like:

- circadian_lighting tries to change color_temp to 500
- the light changes briefly to 500 but flips immediately to the nearest possible value, 454
- circadian_lighting is not happy with this, and again sets the value to 500
- and so on...

These sequences creates a lot of events, and my `events` table is filled with maybe 10 events every second:

```
MariaDB [hassio]> select event_type, created from events order by event_id desc limit 20;
+---------------+---------------------+
| event_type    | created             |
+---------------+---------------------+
| call_service  | 2019-05-04 19:38:07 |
| state_changed | 2019-05-04 19:38:07 |
| state_changed | 2019-05-04 19:38:07 |
| state_changed | 2019-05-04 19:38:07 |
| call_service  | 2019-05-04 19:38:07 |
| state_changed | 2019-05-04 19:38:07 |
| state_changed | 2019-05-04 19:38:06 |
| state_changed | 2019-05-04 19:38:06 |
| call_service  | 2019-05-04 19:38:06 |
| state_changed | 2019-05-04 19:38:06 |
| state_changed | 2019-05-04 19:38:06 |
| call_service  | 2019-05-04 19:38:06 |
| state_changed | 2019-05-04 19:38:06 |
| state_changed | 2019-05-04 19:38:06 |
| call_service  | 2019-05-04 19:38:06 |
| state_changed | 2019-05-04 19:38:05 |
| state_changed | 2019-05-04 19:38:05 |
| call_service  | 2019-05-04 19:38:05 |
| state_changed | 2019-05-04 19:38:05 |
| state_changed | 2019-05-04 19:38:04 |
+---------------+---------------------+
20 rows in set (0.006 sec)
```

Could this be solved by somehow allowing the values to deviate a bit from what circadian_lighting wants them to be? E.g. only send a new command if the absolute deviation is above some value?

I'm happy to provide my configuration and logs by request :)

**Comment by claytonjn** [comment]
I'll have to think about this, it would complicate things quite a bit. For example, users with short `interval` might fall within the deviation. 

The implementation itself of RaspBee seems pretty bad. Honestly my best advice would be to just use the Hue bridge. It's basically free with the starter kits and in the 4 years I've had Hue lights I've never had a single issue.

**Comment by claytonjn** [comment]
Could you try out [1.0.8b](https://github.com/claytonjn/hass-circadian_lighting/releases/tag/1.0.8b) and see if this fixes your issue?

**Comment by LEJOUI** [comment]
Seems to work over here. Events are a lot less.

**Comment by marhoy** [comment]
@claytonjn Thanks! The 1.0.9b seems to work fine. I don't see a lot of events now :)

And I like the added possibility to use my "manual" dimmer switch without CL immediately readjusting.
