### ISSUE TITLE
brightness in automatizacion

### ISSUE THREAD

**Issue by JosefPRajmon** [claytonjn/hass-circadian_lighting#208]
hello i try create automaion witch circadian lighting but i dont know what is this... "switch.cadian_lighting_[...]" do you everrybody what is this?

**Comment by claytonjn** [comment]
The switch entities are created for each instance of Circadian Lighting - when the switch is turned on the lights will be adjusted automatically according to your configuration, and when the switch is off the lights will not be adjusted. 

If you need more assistance, please use the thread in the Home Assistant forums: https://community.home-assistant.io/t/circadian-lighting-custom-component/

I would like to keep the GitHub issues limited to problems in the code that need to be addressed.
