### ISSUE TITLE
Error after update to HA 2022.11.4 OS9.3

### ISSUE THREAD

**Issue by rrzvv** [claytonjn/hass-circadian_lighting#209]
Hello, after update to HA2022.11.4 OS 9.3 I get this error for every Circadian Lighting switch

Platform error switch.circadian_lighting - cannot import name 'ATTR_WHITE_VALUE' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)

I don`t know what to do :(

**Comment by claytonjn** [comment]
The Home Assistant team deprecated/removed ATTR_WHITE_VALUE. This has been fixed in CL since version 2.1.2, what version of Circadian Lighting are you using?

**Comment by rrzvv** [comment]
Thank you for your answer !!! I don't know what version it was, at least 1 year old :), but I updated the files and everything is ok !
