### ISSUE TITLE
updating  non available devices

### ISSUE THREAD

**Issue by trackhacs** [claytonjn/hass-circadian_lighting#212]
i have some lights which are getting hard electrical cut from power.

this integration still tries to set updated values and this triggers a lot of error messages on zigbee network. 

for context:  this does not happen with the older integration without GUI.

**Comment by claytonjn** [comment]
I still haven't gotten around to updating this integration for the UI config flow so this integration can only be configured with YAML. I assume you're using some other, unrelated integration.
