### ISSUE TITLE
Brightness not adjusting

### ISSUE THREAD

**Issue by alistairg** [claytonjn/hass-circadian_lighting#23]
I'm likely doing something wrong - but brightness doesn't seem to auto adjust. From my read of the code, line 238 of switch.py just chooses "max brightness" every time - unless sleep mode is on.

Is that what's supposed to happen?

I'd have expected that block of code to be more like:

`def calc_brightness(self):
        if self._attributes['disable_brightness_adjust'] is True:
            return None
        else:
            if self.is_sleep():
                _LOGGER.debug(self._name + " in Sleep mode")
                return self._attributes['sleep_brightness']
            else:
                return ((self._attributes['max_brightness'] - self._attributes['min_brightness']) * ((self._cl.data['percent']) / 100)) + self._attributes['min_brightness']`

**Comment by claytonjn** [comment]
CL is designed to mimic natural lighting. Once the sun has risen, the level of daylight remains relatively constant until sunset (excepting weather conditions). Therefore, CL keeps lights at 100% brightness from sunrise to sunset, and then dims the lights from sunset to sunrise - mimicking twilight behavior. 

Here's a good representation: https://www.weather.gov/images/fsd/astro/twilight.png

**Comment by xconstarx** [comment]
Hey just have a question.

![IMG_20200927_184740](https://user-images.githubusercontent.com/47308722/94370807-66b29f80-00f2-11eb-829d-b7e91e63d845.jpg)

Is the percentage value the value of the brightness?

If so I would have the problem that my brightness doesn't adjust just stays on 100%. 

Or is there anyway to see what the actual brightness given from the component is? So maybe I'm just to impatient to and the value is still 100% by the explanation from you above.

Tryed sleep function and there the brightness lowers to sleep brightness level. So maybe I'm really just to impatient. But also want to understand that sensor.

**Comment by basnijholt** [comment]
if you look at the images/graphs in the README you will understand what is happening.

**Comment by claytonjn** [comment]
@xconstarx the sensor state is the percentage of the sun above/below the horizon. Brightness is included as an attribute of the switch, and will stay at 100% until after sunset.
