### ISSUE TITLE
Multiple disable entities or sleep entity with 0 brightness

### ISSUE THREAD

**Issue by ahmadtawakol** [claytonjn/hass-circadian_lighting#24]
So I want to disable this switch under two conditions, either when the room is empty or when I am sleeping. I have it set to disable when the room is empty, but I can't set the sleep brightness to 0 (the minimum is 1).

**Comment by claytonjn** [comment]
There's no easy way in YAML to define multiple disable entities. I could have `disable_entity_1`, `disable_entity_2`, etc. but that's still a finite amount and there would always be someone for whom there isn't enough. 

I could allow for 0 brightness for in "sleep mode" but there's inconsistency in integrations - some turn on when setting 0 brightness, some turn off, etc. 

The easiest and most robust solution is to use automations to turn on/off the CL switch. In your case you just use an automation to turn off the CL switch when the room is empty or when you're sleeping, and you turn the CL switch back on when the room is not empty and you're not sleeping.
