### ISSUE TITLE
Allow configuring "initial transition"

### ISSUE THREAD

**Issue by claytonjn** [claytonjn/hass-circadian_lighting#35]
Circadian Lighting currently is hardcoded to a 1 sec transition when a light is turned on, so that it will immediately be set to the proper value. I could make this configurable. 

My only hesitation in doing so is that Circadian Lighting already has relatively complex configuration options and I don't want to add unnecessary confusion. Perhaps I should remove the options for disable entity and disable state because very simple automations could be written to turn on/off the CL switch... 🤔

**Comment by rschuiling** [comment]
Personally, I did configure a 3 second transition for my own circadian solution. This gives a smoother experience. In my case, I want the brightness to adjust rather quick (3 seconds) then after that color temperature may take a little longer (7 seconds). This is Tradfri hence two separate calls by the way. 

So yes I think it would be a good feature.

**Comment by bouwew** [comment]
I don't care about this so please make use of the default-mechanism in HA.

**Comment by LEJOUI** [comment]
I’d like to see this option!

**Comment by mouth4war** [comment]
Will this fix the issue where if you turn a light on with a transition, circadian kicks in before the transition is complete, ruining the transition.

**Comment by broyuken** [comment]
> Will this fix the issue where if you turn a light on with a transition, circadian kicks in before the transition is complete, ruining the transition.
> 
> EDIT: Yes, it does.

This is exactly what I’m looking to fix. How would I implement this until it gets pulled into the main code in HA?

**Comment by claytonjn** [comment]
https://github.com/claytonjn/hass-circadian_lighting/blob/20d75ada87660226025f4b6850ae78dfa6b4ff87/custom_components/circadian_lighting/switch.py#L48

@broyuken just change that line in your local switch.py file in custom_components

**Comment by claytonjn** [comment]
There is now a `initial_transition` configuration option at the switch level. Leaving this open because I have to update the WiKi once this hits master.

**Comment by claytonjn** [comment]
`initial_transition` added to master, wiki updated.
