### ISSUE TITLE
Make transition between brightness-only switches faster

### ISSUE THREAD

**Issue by bouwew** [claytonjn/hass-circadian_lighting#36]
For some of my lights I have two separate brightness-switches:
- a switch with a low brightness setting for when no one is in the area
- a 2nd switch with a higher brightness setting for when someone enters the area.

When switching between these 2 switches, I would like to have a faster transition than the transition-setting in configuration.yaml, for instance similar to when switching on a light as described in #35,

**Comment by claytonjn** [comment]
Actually I just saw this but it should be fixed in [1.0.9b](https://github.com/claytonjn/hass-circadian_lighting/releases/tag/1.0.8b).

**Comment by gericho** [comment]
the link takes to 1.0.8b

**Comment by bouwew** [comment]
Thanks!! I will test and report back.

**Comment by bouwew** [comment]
Tested: v1.0.9b works as requested :)
Thanks!!
