### ISSUE TITLE
Add documentation for updating hue scenes

### ISSUE THREAD

**Issue by gderber** [claytonjn/hass-circadian_lighting#49]
I've been struggling to get this to work on my own.  I really appreciate the work that has been put into this.  Adding in the documentation for updating hue scenes would be extremely helpful. 

[Wiki: Additional Functionality ](https://github.com/claytonjn/hass-circadian_lighting/wiki/Additional-Functionality)

**Comment by claytonjn** [comment]
Duplicate of #3 - I will get to this as soon as I have time.
