### ISSUE TITLE
Circadian sensor detail window

### ISSUE THREAD

**Issue by ahartman** [claytonjn/hass-circadian_lighting#54]
Clicking on the circadian sensor at the top of the Lovelace screen opens a small detail window.
There is no value in displaying X decimals here, figures without decimals would be much clearer/simpler and formatting would be much better.

One question: sometimes I see negative percentages in this window, what do they mean or are they a bug?

Apart from this, a wonderful plugin, powerful and runs 'out of the box'.

Regards, ahartman, belgium

**Comment by claytonjn** [comment]
I agree, I should probably just round everything to integers. 

Negative percentages occur when the sun is below the horizon.

**Comment by ahartman** [comment]
If you ever open up that window code, I would also appreciate display of the brightness.
I realize this can be different for different light groups. However, what you could display is the calculated brightness, no matter that individual light groups can deviate from that with max and min settings.
