### ISSUE TITLE
Automation Assistant / light turn on with correct temp or brightness

### ISSUE THREAD

**Issue by dede34fr** [claytonjn/hass-circadian_lighting#61]
Hi,
when using the HA Automation Assistant (editor), data_template seems not allowed. Getting message "service data_template not allowed"
Added in the action panel (service data box) the correct light entity id:
  data_template:
    entity_id: light.entity
    kelvin: "{{ state_attr('sensor.circadian_values', 'colortemp') | int }}"
    brightness_pct: "{{ state_attr('switch.circadian_lighting_[...]', 'brightness') | int }}"
Seems it does not work this way. Also got the same error using /developer-tools/service.
See :
https://github.com/claytonjn/hass-circadian_lighting/wiki/Additional-Functionality

**Comment by claytonjn** [comment]
I've been looking at that (see issue #38). If data templates aren't allowed using the frontend editor then you simply have to edit automations.yaml directly if you want this functionality.

**Comment by JSchoeck** [comment]
Data templates are allowed via the UI ediotr (at least since the last HA release).
@dede34fr find two ways that work in the linked issue.
