### ISSUE TITLE
Negative Values (State)

### ISSUE THREAD

**Issue by Kylespamaccoun7** [claytonjn/hass-circadian_lighting#62]
The state has been returning negative values since install.  Just now realizing that this is supposed to be the brightness.  Last night, for example, it was at 0 at 5:00pm, and -100 at 12:00pm.  It seems to be at its highest at around 12:00 noon.  At 7:00am this morning, it turned from negative values to positive.

I manually input the lat/long in case there was an issue with using the hass-determined-location, but that didn't fix it.

Searching, I only saw one other similar issue, and that ended up being related to calculations. But since my time-zone (West Coast/United States) is somewhat common, I feel like I wouldn't be the first to have this issue.

Can you let me know: 1) what information I should be looking at and (if it rises to the level of something I can't fix myself), 2) what information I should provide in order to obtain help.  (I've seen you request logs on other issues.  Are these logs obtained by adjusted the logger value in home assistant and including the component/sensor in the configuration?)

Thank you for all the help.  

![circ sensor capture 1 14 20](https://user-images.githubusercontent.com/46274294/72358859-17325d80-36a2-11ea-86cc-41bd8c331ca2.PNG)

**Comment by claytonjn** [comment]
That's exactly how it's supposed to work. The `sensor.circadian_values` represents the best calculation of the suns percentage above (+) and below (-) the horizon, it is *not* brightness. Brightness is an attribute of each CL switch because it can differ based on how each switch is configured.
