### ISSUE TITLE
Tradfri using Deconz does not adjust color

### ISSUE THREAD

**Issue by FunPsycho** [claytonjn/hass-circadian_lighting#65]
I'm using CT lighting because I have the White dimable [tradfri](https://www.ikea.com/us/en/p/tradfri-led-bulb-e26-1000-lumen-wireless-dimmable-white-spectrum-opal-70408492/) bulb with Deconz. It moves the brightness up and down as I would suspect but it does not move the color.

So I am using brightness in the config and it seems to be working fine.

**Comment by claytonjn** [comment]
I believe the tradfri lights don't allow adjusting brightness and color at the same time. The best solution is to configure one switch for brightness and one switch for color temperature.

**Comment by FunPsycho** [comment]
Ok I think I need to raise this with the Home Assistant repository.  I'm using the Add-on, I think I might try the API if that is easier.
