### ISSUE TITLE
Is it possible to set different min_colortemp and max_colortemp for individual lights?

### ISSUE THREAD

**Issue by Luklek** [claytonjn/hass-circadian_lighting#80]
I am using 2 different brands of light bulbs next to each other and for the same colortemp they have a quite different color.
So I would like to have different set of colortemp for each different ligth. Is this possible? (sorry I am very new to this)

**Comment by claytonjn** [comment]
Not currently, _probably_ not ever because ultimately that's an issue with the lights themselves. 

See more info here: #29 

What is more likely is that I will implement #56

Closing because this is a duplicate. Please continue conversation in one of the above issues.
