### ISSUE TITLE
Issues with HA 0.108.0-5

### ISSUE THREAD

**Issue by jes1417** [claytonjn/hass-circadian_lighting#85]
I have been having weird flickering issues with lights after I updated to 0.108.0, I also noticed that my switches are no longer working. 

If I turn off my circadian light switch lights will still dim over time. Even after uninstalling from HACS and rebooting HA the lights still dimmed. I had to comment out the switch config to get them to stop.

Everything has worked perfectly for months and after the update I noticed these issues.

**Comment by claytonjn** [comment]
I've been on 0.108.x for a couple days and everything is working correctly. Have you turned on debug logging to try to better see what's going on?

**Comment by jes1417** [comment]
So after removing everything and reading it's all working again as expected 🤷‍♂️

**Comment by sovanyio** [comment]
Facing this issue also @jes1417, do you mean a complete, from scratch install of HASS? :O

**Comment by jes1417** [comment]
No, I removed the component from HACS and commented out everything in my config from the integration. Then restarted HASS and added it back to HACS and uncommented the config and rebooted again.
