### ISSUE TITLE
Featue Request: Min Max Kelvin

### ISSUE THREAD

**Issue by poudenes** [claytonjn/hass-circadian_lighting#88]
Hi All,

I use this add-on for a while, love it so much!!!! Thanks!!!

Would be great to add min_kelvin and max_kelvin.
So you can set your own kelvin range. I don't like almost full white (daylight) want it little bit more warmer... 

Cheers
Peter

**Comment by claytonjn** [comment]
You mean this?
https://github.com/claytonjn/hass-circadian_lighting/wiki/Advanced-Configuration#component-configuration-variables

**Comment by poudenes** [comment]
Ohh my .... I read that page... damn... first 2 lines ... corona have eaten my brains... haha SORRY!!!

Thanks !!!

Case closed.. :D
