### ISSUE TITLE
is this for hue only?

### ISSUE THREAD

**Issue by mac-city** [claytonjn/hass-circadian_lighting#9]
this sound great and one of the main reasons i started getting into home assistant a few weeks ago.  i am transitioning from hue to wifi rbg bulbs.  i have several installed already.  does it work with both hue and rgb wifi bulbs?

**Comment by claytonjn** [comment]
Absolutely not, it should work with any light entities in Home Assistant! I just happen to have almost exclusively Hue lights throughout my house so there are some Hue-specific things that I have set up in my own instance.
