### ISSUE TITLE
Warning: SwitchDevice is deprecated, modify CircadianSwitch to extend SwitchEntity

### ISSUE THREAD

**Issue by kaosmagix** [claytonjn/hass-circadian_lighting#93]
Home Assistant 0.110.0b2

SwitchDevice is deprecated, modify CircadianSwitch to extend SwitchEntity

This warning appears in the logs when starting HA (also for a few other custom components).

(No idea what it entails but as it is a deprecation warning I thought it would be useful to know)

Thanks for this great component!

**Comment by monotonus** [comment]
Can confirm this for 0.110.2

**Comment by mikeage** [comment]
There's a PR to fix this at #92

**Comment by claytonjn** [comment]
Fixed in beta 1.0.13b, will push to general release if no issues are reported in the next couple days.

**Comment by poudenes** [comment]
Great, hope to see soon a update in HASC :D

**Comment by claytonjn** [comment]
@poudenes you could have updated though HACS by switching to beta releases for Circadian Lighting but no need to now, I just pushed it to the general release. :)
