### ISSUE TITLE
CL not found in HACS ???

### ISSUE THREAD

**Issue by PieBru** [claytonjn/hass-circadian_lighting#99]
Hi,
I just installed HACS on my RasPI4 HassOS server, but can't find the Circadian Lighting integration.
I feel dumb, what did I miss?
Piero

Edit: obviously I completed the HACS installation and I'm able to find all my other usual HACS integrations.

![Screenshot from 2020-06-14 19-15-12](https://user-images.githubusercontent.com/6537434/84599680-221d3400-ae74-11ea-8df6-523f675b7593.png)

```
arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.8
installation_type | Home Assistant
os_name | Linux
os_version | 5.4.42-v8
python_version | 3.7.7
supervisor | 227
timezone | Europe/Rome
version | 0.111.2
virtualenv | false
```

**Comment by claytonjn** [comment]
You have to hit the plus sign in the lower right and search there.

**Comment by PieBru** [comment]
Aaaargh!!! I was confused by the new HACS UI.
Definitely it isn't a CL problem.
Thanks for the reply,
Piero
